opts:
  backend:
    select: kube
    kube:
      enable: true
      dir: /mnt/data/zeta-test
      namespace: zeta
      volumes:
        zeta-efs-pvc:
          mount: /mnt/data

      user:
        uid: 1000
        gid: 1000

      predefined_pod_specs:
        scheduler:
          nodeSelector:
            rarg/node-class: compute
            rarg/instance-type: m6i.large
            rarg/capacity-type: ON_DEMAND
        tiny:
          nodeSelector:
            rarg/node-class: compute
            rarg/instance-type: m5.large
            rarg/capacity-type: ON_DEMAND
        thin:
          nodeSelector:
            rarg/node-class: compute
            rarg/instance-type: m5.2xlarge
            rarg/capacity-type: ON_DEMAND
        pudgy:
          nodeSelector:
            rarg/node-class: compute
            rarg/instance-type: m5.4xlarge
            rarg/capacity-type: ON_DEMAND
        fat:
          nodeSelector:
            rarg/node-class: compute
            rarg/instance-type: m5.8xlarge
            rarg/capacity-type: ON_DEMAND


      ## default type to use
      job_pod:
        type: tiny

      env:
        NUMBA_CACHE_DIR: /mnt/data/zeta-test
        CONFIGURATT_CACHE_DIR: /mnt/data/zeta-test
